### ISSUE TITLE
Add CSV export

### ISSUE THREAD

**Issue by ejfox** [bradoyler/googlesheets-reader#1]
Would love the ability to export CSV with this as well with an option

**Comment by ejfox** [comment]
Ah it might be easier just to grab the key and download the URL from here `https://docs.google.com/feeds/download/spreadsheets/Export?key=INSERTKEYHERE&exportFormat=csv `

**Comment by bradoyler** [comment]
well, my plan was to deprecate this lib in favor of this: https://github.com/bradoyler/googlesheet-to-json

**Comment by ejfox** [comment]
ah, I was looking for something that wouldn't require oauth / google drive

**Comment by bradoyler** [comment]
yea, that is simply an http request. But requires that sheet is setup with public permissions.
